pipeline {
  agent {
    label 'esbtpt1ecd001'
  }
  stages {
    stage('checkout beats source code') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/7.11']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '465cc7bc-0bd5-4a56-92da-ff33fdd2952c', url: 'https://github.com/jockjiang/beats.git']]])
        }
      }
    stage('build filebeat'){
      steps {
        sh '''export GOROOT=/data/go1.15.8
              export PATH=$PATH:$GOROOT/bin
              export GOPATH=/data/gopath
              export PATH=$PATH:$GOPATH/bin
              export GOPRIVATE="github.com/jockjiang,sqbu-github.cisco.com/SAP,sqbu-github.cisco.com/WAP-DPI"
              go mod download sqbu-github.cisco.com/SAP/kmsgowrapper
              go mod download sqbu-github.cisco.com/WAP-DPI/webexpii
              cd filebeat
              mage build
              mkdir -p /tmp/jenkins/filebeat
              cp ./filebeat /tmp/jenkins/filebeat'''
      }
    }
    stage('checkout webex filebeat modules'){
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'jockj_sqbu-github', url: 'https://sqbu-github.cisco.com/WAP-DPI/filebeat-modules.git']]])
        sh ''' mkdir -p /tmp/jenkins/filebeat_modules
               cp -R ./* /tmp/jenkins/filebeat_modules
               rm -f /tmp/jenkins/filebeat_modules/filebeat-modules.spec
               rm -f /tmp/jenkins/filebeat_modules/build-rpm.sh
        '''
      }
    }
    stage('checkout filebeat package'){
      steps {
        checkout([$class: 'GitSCM', branches: [[name: 'refs/tags/v7.11.2-19']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'jockj_sqbu-github', url: 'https://sqbu-github.cisco.com/WAP-DPI/filebeat.git']]])
        sh ''' cp -f /tmp/jenkins/filebeat/filebeat ./usr/share/filebeat/bin
               cp -f -R /tmp/jenkins/filebeat_modules/* ./usr/share/filebeat/webex_module
               rm -fr ./filebeat
               export VERSION=7.11.2
               export BUILD_NUMBER=19
               ./build-rpm.sh
               rm -fr /tmp/jenkins
               rm -fr ./*
        '''
      }
    }
  }
}
