pipeline {
  agent {
    label 'esbtpt1ecd003'
  }
  parameters {
    string(name: 'Elasticsearch_Version', defaultValue: '7.10.2' , description: 'Please input the Elasticsearch Version.',trim:true)
  }
  stages {
    stage('checkout elasticsearch source code') {
      steps {
        //checkout([$class: 'GitSCM', branches: [[name: "refs/tags/v${Elasticsearch_Version}-${env.BUILD_NUMBER}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '465cc7bc-0bd5-4a56-92da-ff33fdd2952c', url: 'https://github.com/jockjiang/elasticsearch.git']]])
        checkout([$class: 'GitSCM', branches: [[name: '*/7.10']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '465cc7bc-0bd5-4a56-92da-ff33fdd2952c', url: 'https://github.com/jockjiang/elasticsearch.git']]])
        }
      }
    stage('build elasticsearch'){
      steps {
        sh '''export JAVA_HOME=/usr/share/elasticsearch/jdk
              ./gradlew localDistro
        '''
      }
    }
    
    stage('checkout elasticsearch package'){
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'jockj_sqbu-github', url: 'https://sqbu-github.cisco.com/WAP-DPI/elasticsearch.git']]])
        sh """export VERSION=${Elasticsearch_Version}
              export BUILD_NUMBER=${env.BUILD_NUMBER}
              export build_path=build/distribution/local/elasticsearch-${Elasticsearch_Version}-SNAPSHOT/
              export dest_path=usr/share/elasticsearch/
              ./build-rpm.sh
        """
      }
    }
    
  }
}
