pipeline {
  agent {
    label 'esbtpt1ecd403'
  }
  stages {
    stage('checkout wappii') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'jockj_sqbu-github', url: 'https://sqbu-github.cisco.com/WAP-DPI/logstash-filter-wappii.git']]])
        }
      }
      stage('build plugin'){
        steps {
          sh '''
                ./gradlew gem'''
        }
      }
    }
}